### ISSUE TITLE
JReleaser

### ISSUE THREAD

**Issue by unknowIfGuestInDream** [unknowIfGuestInDream/windowMonitor#6]

**Comment by unknowIfGuestInDream** [comment]
GitHub action 打包native Image
准备 .jreleaser/config.yml

假设你的项目是 Java CLI，com.example.Main 是主类：
```
project:
  name: myapp
  version: 1.0.0
  description: My Java CLI app with native image

java:
  version: 17
  mainClass: com.example.Main

nativeImage:
  active: ALWAYS
  imageName: myapp
  executable:
    name: myapp
  graal:
    enabled: true
    javaHome: $JAVA_HOME
    mainClass: com.example.Main
  args:
    - "--no-fallback"
    - "--enable-https"

```

新建 .github/workflows/release.yml：
```yaml
name: Release Native Image

on:
  push:
    tags:
      - 'v*'        # 触发条件：打 tag 如 v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GraalVM
        uses: actions/setup-java@v3
        with:
          distribution: 'graalvm'
          java-version: '17'
          cache: 'native-image'

      - name: Install native-image tool
        run: gu install native-image

      - name: Setup JReleaser CLI
        run: |
          curl -sL https://github.com/jreleaser/jreleaser/releases/latest/download/jreleaser-cli-linux-amd64.tar.gz | tar xz -C /usr/local/bin --strip-components=1 jreleaser-cli/bin/jreleaser
          chmod +x /usr/local/bin/jreleaser

      - name: Run JReleaser assemble
        run: jreleaser assemble

      - name: Upload native image artifact
        uses: actions/upload-artifact@v3
        with:
          name: native-image
          path: out/jreleaser/assemble/myapp/native-image/myapp

```

说明
on.push.tags: 只有推送 v* 标签才触发，保证发布流程规范；

actions/setup-java@v3 使用 GraalVM 17 并缓存 native-image；

手动下载安装最新 JReleaser CLI；

运行 jreleaser assemble 自动构建 native image；

构建产物作为 artifact 上传到 workflow 页面供下载；

可选发布步骤
```yaml
- name: Run JReleaser release
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: jreleaser release

```

**Comment by unknowIfGuestInDream** [comment]
修改 .github/workflows/release.yml
```yaml
name: Release Native Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GraalVM
        uses: actions/setup-java@v3
        with:
          distribution: 'graalvm'
          java-version: '17'
          cache: 'native-image'

      - name: Install native-image tool
        run: gu install native-image

      - name: Setup JReleaser CLI
        run: |
          curl -sL https://github.com/jreleaser/jreleaser/releases/latest/download/jreleaser-cli-linux-amd64.tar.gz | tar xz -C /usr/local/bin --strip-components=1 jreleaser-cli/bin/jreleaser
          chmod +x /usr/local/bin/jreleaser

      - name: Run JReleaser assemble
        run: jreleaser assemble

      - name: Upload native image artifact
        uses: actions/upload-artifact@v3
        with:
          name: native-image
          path: out/jreleaser/assemble/myapp/native-image/myapp

      - name: Publish Release to GitHub (optional)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: jreleaser release

```

新增了步骤 Publish Release to GitHub (optional)

仅当触发为 tag push 且 tag 以 v 开头时执行；

需要仓库 secrets 中自动有 GITHUB_TOKEN（默认存在）；

jreleaser release 会根据 .jreleaser/config.yml 的 release 配置自动上传打包产物到 GitHub Release。

.jreleaser/config.yml Release 配置示例
替换 owner 和 repo 为你的仓库信息
```yaml
release:
  github:
    owner: your-github-username-or-org
    repo: your-repo-name
    token: '${env.GITHUB_TOKEN}'
    announce: true
    changelog:
      enabled: true

```
